pipeline {
    agent any
    
    stages {
        stage('build') {
            steps {
            	sh 'pwd'
            	sh 'ls -lrth'
            	
            	dir('sb-jenkins') {
            	    sh 'pwd'
            	    sh 'ls -lrth'
            	    sh 'chmod +x mvnw'
				    sh './mvnw package'    
            	}
            }
        }
    }
}