pipeline {
    agent any
    
    stages {
        stage('deploy') {
            steps {
            	sh 'pwd'
            	dir('sb-jenkins') {
            		sh 'pwd'
					sh './gradlew bootRun'
            	}
            }
        }
    }
}