pipeline {
    agent any
    
    stages {
        stage('deploy') {
            steps {
            	sh 'pwd'
            	sh 'ls -lrth'
            	
            	dir('sb-jenkins-gradle') {
            	    sh 'pwd'
            	    sh 'ls -lrth'
            	    sh 'chmod +x gradlew'
				    sh './gradlew bootJar'    
            	}
            }
        }
    }
}